### ISSUE TITLE
关于Debian镜像源的疑问

### ISSUE THREAD

**Issue by wfwzhxd** [cqumirror/feedback#1]
以前是有debian源的，不知道现在怎么没有了，觉得debian用的人也不少哇

**Comment by rhiswell** [comment]
镜像一套 debian 源可能带来至少 2.5T 流量，这需要一个稳定的上游源。我试试看。

**Comment by rhiswell** [comment]
已镜像 debian/debian-cd/debian-security/debian-multimedia

**Comment by wfwzhxd** [comment]
thanks~
