### ISSUE TITLE
建议增加 Google Flutter 源

### ISSUE THREAD

**Issue by lanlin** [cqumirror/feedback#10]
希望能够增加 Google Flutter 源，谢谢。

**Comment by fengzipei** [comment]
您好，由于该项目相对冷门，加之目前镜像站还有一些事情需要处理以及 VPS 流量限制，所以近期不会进行镜像。您可以考虑使用现有的国内其它 Google Flutter 镜像：
1. PUB_HOSTED_URL=https://pub.flutter-io.cn
    FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
2. PUB_HOSTED_URL: https://dart-pub.mirrors.sjtug.sjtu.edu.cn/
    FLUTTER_STORAGE_BASE_URL: https://mirrors.sjtug.sjtu.edu.cn/

感谢您的建议！

**Comment by lanlin** [comment]
哦，这样子啊。感谢您的回复，我已经调整到其他镜像了，谢谢！
