### ISSUE TITLE
新增MX Linux / Antix镜像

### ISSUE THREAD

**Issue by aledie** [cqumirror/feedback#13]
项目名称与简介(Project Intro.)
https://mxlinux.org
https://distrowatch.com/table-mobile.php?distribution=mx

中文：
https://www.linuxidc.com/Linux/2018-03/151387.htm

上游地址与镜像方法(How to Mirror)
https://mxlinux.org/wiki/rsync-server/mirroring-mxantix-linux

其他信息(Other)
镜像大小(Mirror Size):
MX-ISOs: 35 Gb
MX-Packages: 160 Gb

**Comment by aledie** [comment]
谢谢 😊

**Comment by xterat** [comment]
@aledie Sorry, 我误以为它一直在同步. 
我现在换成了从 TUNA 那里同步, 非常感谢你的反馈 🙏.

**Comment by aledie** [comment]
@xterat: 谢谢！但请再次检查。即使切换到TUNA后，同步似乎也没有进展

**Comment by xterat** [comment]
@aledie 好的, 现在已经同步了 54/160 GB 了, 速度大概是 2~4 MB/s, 预计还需要 10+ 个小时才能同步完~

**Comment by aledie** [comment]
谢谢，这很棒。我只是担心可能出现了问题...😁

**Comment by aledie** [comment]
@xterat: 你好。 mx-packages的同步现在似乎已成功完成。😁
你是否还计划镜像mx-isos（我可以在我们的iso下载页面上列出CQU），或者只是mx-packages？再次感谢你的帮助!

**Comment by xterat** [comment]
@aledie 没问题, 我等一下把 mx-isos 也同步了~ 多谢关注 😃

**Comment by aledie** [comment]
@xterat: 谢谢！

**Comment by aledie** [comment]
@xterat: MX-ISO同步已经持续太久不停，可能有问题。你能检查一下吗？也许是因为来自中国以外？或者超时生成NAT，可以尝试“ServerAliveInterval 5”。或者从TUNA完成初始同步。

**Comment by aledie** [comment]
@xterat: 我现在发现美国的MX-ISO已停机维修，可能需要1-2天。可以等待或使用TUNA。

**Comment by xterat** [comment]
@aledie 你好, 我发现 MX-ISOs 镜像实际上已经同步好了, 应该是主要上的状态更新有点问题, 估计等一下就好了~

**Comment by aledie** [comment]
@xterat: 我刚才看到，看起来不错。谢谢,😁

**Comment by aledie** [comment]
@xterat：你能看看吗？自2019-01-15 08:55以来，MX-Linux同步已经持续了很长时间.

**Comment by xterat** [comment]
@aledie 好像是因为网络问题导致同步卡住了, 现在应该已经同步好了. 谢谢你的提醒🙏🙏

**Comment by aledie** [comment]
@xterat: 谢谢😁

**Comment by aledie** [comment]
@xterat：你能看看吗？自2019-01-18 13:03以来，MX_Linux同步已经持续了很长时间.
好像我们很快就会成为最好的朋友😆

**Comment by xterat** [comment]
@aledie 😂😂不好意思, 这次也是网络问题卡住了. 但是我暂时还没有找到好的方法来检测这种问题... 我以后会每天检查一下~~

**Comment by aledie** [comment]
@xterat: 你好！在上游删除后，您的MX镜像似乎保留旧文件。也许你可以在你的rsync命令中添加像--delete-delay这样的东西？它会保持最新状态并释放一些磁盘空间
