### ISSUE TITLE
新增镜像 KiCad

### ISSUE THREAD

**Issue by taotieren** [cqumirror/feedback#15]
KiCad 下载
请介绍新镜像
* 上游源（官方镜像）的地址
    https://kicad-downloads.s3.cern.ch/index.html?prefix=
* 该项目的介绍
    开源的 原理图 和 PCB 设计工具
* 为什么希望添加该镜像
    方便国内电子设计者下载和使用开源的 EDA 工具，避免使用盗版的 AD 等 非正版的 EDA设计工具。

**Comment by weearc** [comment]
请暂时再等待一下，我们刚刚添置了新硬件，目前大半镜像仍处于初始化状态。待全部镜像初始化完成会再对该仓库进行镜像。

**Comment by taotieren** [comment]
@weearc 快过了一个月了吧，那些镜像初始化完成了吗？

**Comment by weearc** [comment]
@taotieren 您好，我们近期进行了部分改造，目前的话正在准备添加kicad。初次开始同步时将通知您。

**Comment by taotieren** [comment]
https://github.com/tuna/mirror-web/blob/master/_posts/help/2019-07-23-kicad.md
对应的 help 文件

**Comment by taotieren** [comment]
我抽空再把 help 文件改改
写的更通俗易懂一些
一些插件可以单独拿出来说明

**Comment by weearc** [comment]
@taotieren KiCad 已经开始同步，地址： https://mirrora.cqu.edu.cn/kicad/

**Comment by weearc** [comment]
非常，非常，非常抱歉花了这么长时间（近四个月）才开始同步。中间也出了很多事故（包括造轮子重写s3 bucket同步工具）希望能得到您的谅解… 帮助文件将在稍后几天加入

**Comment by taotieren** [comment]
非常感谢
