### ISSUE TITLE
希望增加raspbian 镜像

### ISSUE THREAD

**Issue by microestc** [cqumirror/feedback#16]
希望增加raspbian 镜像

**Comment by weearc** [comment]
好的，请求我们已经收到，会逐步进行同步，请耐心等待。目前仍在初始化其他镜像，raspbian权重稍低要等一阵子。

**Comment by weearc** [comment]
@microestc raspbian已经开始同步。初次同步结束后会通知您。

**Comment by microestc** [comment]
感谢
