### ISSUE TITLE
mirrors.cqu.edu.cn 主页上的链接错误

### ISSUE THREAD

**Issue by Hagb** [cqumirror/feedback#19]
mirrors.cqu.edu.cn 主页上的“重大蓝盟”链接写成了 https 协议的。

**Comment by weearc** [comment]
> mirrors.cqu.edu.cn 主页上的“重大蓝盟”链接写成了 https 协议的。

并非https， 请在开发者工具中查阅。

**Comment by Hagb** [comment]
> > mirrors.cqu.edu.cn 主页上的“重大蓝盟”链接写成了 https 协议的。
> 
> 并非https， 请在开发者工具中查阅。

额开发者工具里面也是https呀。
`curl http://mirrors.cqu.edu.cn/ -s | grep 重大蓝盟`得到的也是
`<li><a href="https://lanunion.cqu.edu.cn" target="_blank">重大蓝盟</a></li>`
