### ISSUE TITLE
建议新增raspberrypi 源

### ISSUE THREAD

**Issue by ykla** [cqumirror/feedback#22]
树莓派的 archive.raspberrypi.org 软件源即 /etc/apt/sources.list.d/raspi.list 文件中的源
目前国内罕有镜像

**Comment by hmsjy2017** [comment]
国内已经有很多了
推荐使用中科大软件源
https://mirrors.ustc.edu.cn/help/raspberrypi.html
或者上海交大
https://mirrors.sjtug.sjtu.edu.cn/docs/raspberrypi

**Comment by weearc** [comment]
考虑到该发行版默许向微软对用户个人信息进行汇报等操作，并且其开发者对此的态度令人难以接受。我们 ***永远*** 不会考虑也 ***永远***不会添加该仓库。原 raspbian 仓库目前仍可用。我们也推荐使用其他发行版作为 OS 软件使用。
