### ISSUE TITLE
R语言镜像403了

### ISSUE THREAD

**Issue by Mapaler** [cqumirror/feedback#25]
点击首页的下载Windows版就会403
![图像 1](https://user-images.githubusercontent.com/6565860/90646148-72948180-e269-11ea-9a0c-a7f1d9fb303f.png)

这是其他学校的正常镜像
![图像 3](https://user-images.githubusercontent.com/6565860/90646275-9fe12f80-e269-11ea-928d-81f92e509bac.png)

**Comment by weearc** [comment]
@Mapaler 感谢回复，确定为同步时目录权限出现问题，已经修复

**Comment by Mapaler** [comment]
https://mirrors.cqu.edu.cn/CRAN/doc/manuals/r-release/R-intro.html
手册页面也都是403

**Comment by weearc** [comment]
> https://mirrors.cqu.edu.cn/CRAN/doc/manuals/r-release/R-intro.html 手册页面也都是403

确认此次问题来源为上游权限设置出错，已修复
