### ISSUE TITLE
[Misc] 请求贵站加入 mirrorz.org

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [cqumirror/feedback#27]
最近开发一个项目 https://github.com/ZenithalHourlyRate/mirrorz ，目的是将各个镜像站的信息汇总起来，形成类似黄页的东西，不知道贵站是否有兴趣加入该项目

Demo: [www.mirrorz.org](https://www.mirrorz.org)

**Comment by weearc** [comment]
感谢您的工作！请随意将我们的链接添加至贵站。

**Comment by ZenithalHourlyRate** [comment]
需要贵站提供相应的 `mirrorz.json`，格式在README中有说明，针对常见的同步后端（例如tunasync），在项目中也有成熟的脚本
