### ISSUE TITLE
[Request] OpenWrt 第三方软件源

### ISSUE THREAD

**Issue by hmsjy2017** [cqumirror/feedback#28]
## intro

- name: `OpenWrt 第三方软件源`
- intro_link:<https://github.com/garypang13/OpenWrt>
- storage_link: <rsync://op.supes.top/packages>
- licence:MIT
- size:不超过10G

## descrption and reasons

OpenWrt 第三方源，作为官方源的补充，收录了市面上大部分主流第三方插件，是我见过最好的 OpenWrt 第三方软件源。

**Comment by ZenithalHourlyRate** [comment]
garypang13/OpenWrt#266 ，供参考

**Comment by weearc** [comment]
由于如下原因： https://github.com/garypang13/OpenWrt/issues/266#issuecomment-766087521 该镜像中包含：专有的、未授权的软件包、未获得再分发许可的软件包，本着尊重版权尊重技术的原则，我们将不会考虑添加该第三方仓库。敬请谅解
