### ISSUE TITLE
Update mirror | deepin

### ISSUE THREAD

**Issue by lxwndr** [cqumirror/feedback#29]
Hi,

The deepin distribution repository: [https://mirrors.cqu.edu.cn/deepin/](https://mirrors.cqu.edu.cn/deepin/) has been out of date for a long time.

Can you check the synchronization?

More information: [https://www.deepin.org/zh/mirrors/packages/](https://www.deepin.org/zh/mirrors/packages/)

Best regards.

**Comment by weearc** [comment]
@lxwndr Hi! Our mirror of deepin is already up-to-date. And if you mean the time of file list generated by nginx is outdated, the update time won't change until the directory itself changed. If you have any further questions, please contact us.

Best regard
Op team of Lanunion

**Comment by lxwndr** [comment]
> @lxwndr Olá! Nosso espelho de profundidade já está atualizado. E se você quer dizer que a hora da lista de arquivos gerada pelo nginx está desatualizada, a hora de atualização não mudará até que o próprio diretório mude. Se tiver mais questões, por favor contacte-nos.
> 
> Os meus cumprimentos
> Equipe Op de Lanunion

Is there a contact email? Or should all problems be reported here on GitHub?

Note: I am setting up a list of emails to be published on the deepin website; so that any user can count any mirror, if a problem occurs.

**Comment by Tiger3018** [comment]
The contact email address is `cqumirror@gmail.com`. You can find it in
README.md, and we will provide a English description there.


Thanks.
