### ISSUE TITLE
[Report] 安装镜像无法获取

### ISSUE THREAD

**Issue by July541** [cqumirror/feedback#32]
## intro
安装镜像及应用软件均无法下载

## how to reproduce this bug
点击图中的下载链接
![image](https://user-images.githubusercontent.com/16057632/116029785-a479a580-a68c-11eb-8bd0-90435d042682.png)

**Comment by July541** [comment]
http://mirrors.cqu.edu.cn/static/isoinfo.json 获取到的内容为空

**Comment by Hagb** [comment]
感谢反馈！已修复。
