### ISSUE TITLE
[Request] [新镜像请求] 新增 atzlinux （铜豌豆 Linux）

### ISSUE THREAD

**Issue by taotieren** [cqumirror/feedback#33]
## intro
- name: `atzlinux`
- intro_link: <https://www.atzlinux.com/>
- storage_link: <https://cdn.atzlinux.com/atzlinux>
- licence: GPL 或 软件包自带许可
- size: ≈ 5GB

## descrption and reasons

[铜豌豆 Linux](https://www.atzlinux.com/) 是基于 Debian 的 Linux 中文 开源操作系统。

Debian 是一款非常优秀的 Linux 操作系统，但默认安装缺少中文桌面用户常用的软件。《铜豌豆 Linux》操作系统在 Debian 基础上，收集制作这些常用软件，一次性安装完成，节省大家定制 Debian 的时间,做到“开箱即用”。

同步方式：

    apt-mirror

简单的方法是用 apt-mirror 来同步， 只需要在 /etc/apt/mirror.list 文件里面，加上 ：

    deb https://cdn.atzlinux.com/atzlinux buster  main contrib non-free

**Comment by skyzh** [comment]
快速翻了一下软件列表，有一些软件是不能重分发的（比如 VSCode）。请问仓库的维护者是否有对进入仓库的软件做好了相关的合规性检查？

**Comment by weearc** [comment]
@taotieren 姑且先不提 VSCode 的问题，有些其他的问题希望您能够提供答复：
1. 提供的其他第三方闭源软件是否具有`有法律效力`的再分发许可证明？（包含如：腾讯公司的软件）
2. 除开 `localization` 部分的其他软件包是否与 [Debian](https://mirrors.cqu.edu.cn/debian/) 相同？（包括仓库结构，内容构成等）

基于以上两点，考虑到镜像当前负载，如果具有有效的二次分发许可，则我们期望仅对 ***本地化*** 软件包进行镜像。如果没有明确二次分发许可则将不会进行镜像。另：请提醒该团队停止对 OSDN 进行滥用。

感谢您的谅解和支持，期待您的回复。
