### ISSUE TITLE
[Request] # openEuler

### ISSUE THREAD

**Issue by GeorgeCao-hw** [cqumirror/feedback#36]
## intro

- name: `openEuler`
- intro_link: <https://www.openeuler.org/zh/>
- storage_link: <https://www.openeuler.org/zh/mirror/list/>
- licence: 
- size: 1.8TB

## descrption and reasons

Hello, we are the openEuler Community Infrastructure team.
We hope that the openEuler OS image file can be put online at the site : 'mirrors.cqu.edu.cn'.
Here is a brief introduction to the openEuler community and the openEuler operating system:

openEuler is a free open source Linux distribution. openEuler builds an open, diverse and architecturally inclusive software ecosystem with global developers through an open community format, incubates support for multiple processor architectures, covers the full range of digital facilities, and promotes the prosperous development of enterprise digital infrastructure software and hardware, and application ecology.

Website: https://www.openeuler.org/en/
Email: public@openeuler.io
Repo address: https://repo.openeuler.org/
our_mirror_list: https://www.openeuler.org/zh/mirror/list/

You can synchronize images as follows:
rsync://121.36.97.194/openeuler/
rsync://root@mirror.sjtu.edu.cn/openeuler/

**Comment by weearc** [comment]
@GeorgeCao-hw Hi, OpenEuler is welcomed to our mirror site, but we are currently experiencing a significant lack of space. At present, the remaining space is only 1.1TB, and we still need an additional 1.0TB of it as redundancy for subsequent updates of existing repos. Therefore, for the current situation, it is difficult to mirror OpenEuler. 
In order to ensure a healthy remaining space, we still need an additional 2.8TB to mirror OpenEuler, of which 1.8TB is used for data storage and 1.0TB is used for redundancy during subsequent updates. Thank you for your support and understanding.

**Comment by weearc** [comment]
The expansion thread will be done in this issuse, and if we can solve the array capacity problem, we will discuss the specifics of mirroring.

**Comment by GeorgeCao-hw** [comment]
Thanks for your attention.
Can the storage space of your site store openEuler images?
The openEuler community has been carrying out open source practice activities with many universities ( https://www.openeuler.org/zh/internship/ ).  Many students from Chongqing University are participating in the activities. Therefore, we hope that mirrors.cqu.edu.cn site can provide the OpenEuler images for students.

Best regards.

**Comment by weearc** [comment]
> Thanks for your attention. Can the storage space of your site store openEuler images? The openEuler community has been carrying out open source practice activities with many universities ( https://www.openeuler.org/zh/internship/ ). Many students from Chongqing University are participating in the activities. Therefore, we hope that mirrors.cqu.edu.cn site can provide the OpenEuler images for students.
> 
> Best regards.

Hi, currently we do not have enough space for openEuler. At present, the demand for this distribution in the school has not reached the level of mirroring. We can't provide the necessary storage space for large mirrors with less usage.
