### ISSUE TITLE
建议增加homebrew源

### ISSUE THREAD

**Issue by Vevlins** [cqumirror/feedback#4]
您好！
我是重大在读学生，自一年前便使用重大镜像站的软件源，带来诸多便利，感激之情溢于言表。
今换用macos，遗憾发现并无homebrew源，建议向其他软件镜像站学习，多增加种类。如有能起到微薄帮助的地方，乐意效劳。
祝学习顺利，工作愉快！

**Comment by fengzipei** [comment]
已添加。
