### ISSUE TITLE
[Request] # 请求更新一下conda镜像中pytorch、torchvison的版本

### ISSUE THREAD

**Issue by Opium1715** [cqumirror/feedback#43]
## intro
- name: `pytorch`
- intro_link: <https://download.pytorch.org/whl/>

## descrption and reasons
新版本请求 2.1.2+cu118

**Comment by weearc** [comment]
@Opium1715  Hi，感谢你的反馈。如果你是通过 `pypi` 仓库安装和使用 `pytorch` 等内容的话请参见: https://mirrors.cqu.edu.cn/#/wiki/mirror-wiki/pypi  。只能等待上游仓库更新后才可能从仓库中拉取到对应版本。如果你使用的是 `anaconda` 或 `miniconda` 等发行版，因为我们目前并未对应提供对应镜像，需要你更具体的提供使用信息。
