### ISSUE TITLE
[Request] gentoo-zh (binhost)

### ISSUE THREAD

**Issue by peeweep** [cqumirror/feedback#44]
## intro

- name: `gentoo-zh` (binhost)
- intro_link: <https://github.com/microcai/gentoo-zh>
- storage_link: <rsync://distfiles.gentoocn.org/gentoo-zh/>
- licence:
- size: 11G

## descrption and reasons

https://distfiles.gentoocn.org 是 gentoo-zh overlay 的 distfiles mirror，用于缓存 ebuild 编译所需的源码包

**Comment by weearc** [comment]
Repo's structure changes on server side and initialization work are already underway. This is not a request for new repo. It's a change for current repo mirror

**Comment by weearc** [comment]
Initialization succeeded.
