### ISSUE TITLE
[Report] Archlinux extra 仓库 extra.db 404 Not Found.

### ISSUE THREAD

**Issue by Sving1024** [cqumirror/feedback#46]
## intro

pacman 在尝试获取 extra.db 时返回 404.
![图片](https://github.com/user-attachments/assets/d42863e7-b8f0-4dfd-9d03-022a698e7b31)
浏览器访问也是一样的情况。
![图片](https://github.com/user-attachments/assets/38f22a7f-0b3d-4eac-90ab-90bb11833210)
https://mirrors.cqu.edu.cn/archlinux/extra/os/x86_64/extra.db

## how to reproduce this bug

1. 将`Server = https://mirrors.cqu.edu.cn/archlinux/$repo/os/$arch`  添加到 `/etc/pacman.d/mirrorlist`.
2. 运行 `sudo pacman -Syu`

**Comment by weearc** [comment]
您好，这是一个来自上游的具有一定历史的错误。镜像站只会对上游镜像进行完整的同步，因此任何链接符号或文件缺失如上游以包含此错误则将原封不动同步给下游。
鉴于Arch Linux此问题由来已久并没有得到改善我们建议您择日重新更新系统。

**Comment by Sving1024** [comment]
好吧，感谢回复
