### ISSUE TITLE
同步服务器挂了吗

### ISSUE THREAD

**Issue by ruocan** [cqumirror/feedback#5]
https://mirrors.cqu.edu.cn/status/#syncing-status 上自从2017.11.21后就再也没有同步过了。

**Comment by fengzipei** [comment]
抱歉😣，前段时间由于服务器的硬盘空间满了，导致镜像更新不了。然后又有一些技术问题花了好些时间才解决掉，所以最近才弄好。所有镜像会在这几天同步到最新的状态。
给您带来了不便，真是抱歉。

**Comment by ruocan** [comment]
啊，能修好就行。我们在办公室放了一台服务器，没有接外网，给Ubuntu换重大源的时候才发现这个问题。
感谢你的维护。
