### ISSUE TITLE
一些包的hash值检验总是错误

### ISSUE THREAD

**Issue by zombie110year** [cqumirror/feedback#9]
Failed to fetch http://mirrors.cqu.edu.cn/ubuntu/pool/main/s/snapd/snapd_2.32.9_amd64.deb  Hash Sum mismatch
另外从镜像站下载的texlive2018也是hash检验错误.

**Comment by fengzipei** [comment]
您好，我刚才对比了一下从 http://mirrors.cqu.edu.cn/ubuntu/pool/main/s/snapd/snapd_2.32.9_amd64.deb 下载的文件和从 http://mirrors.ustc.edu.cn/ubuntu/pool/main/s/snapd/snapd_2.32.9_amd64.deb 下载的文件。发现它们是一样的，所以可能不是源的问题。
能不能提供更多的环境信息或是截图呢？这样方便排查错误～

**Comment by zombie110year** [comment]
5b547f6949d9688e56b11633f55806cf  texlive2018.iso 镜像站提供的md5
b3f4d797d81edf6cd13b6d1bb0a2037f  texlive2018.iso 运算得到的md5

**Comment by zombie110year** [comment]
需要怎样的环境信息或截图? 我不知道有哪些因素会造成影响.

**Comment by fengzipei** [comment]
我本地计算结果是一致的诶。可以提供一下校验错误、计算md5的屏幕截图么？

**Comment by zombie110year** [comment]
使用有线网络下载发现hash值检验通过, 使用宿舍无线网络就会错误, 应该是宿舍的路由器有问题......
这个issue应该可以关闭了.
